### ISSUE TITLE
missing predicted value

### ISSUE THREAD

**Issue by ghost** [frahik/BMTME#6]
the model predicted value, e.g. pm$results$Predicated
seems to leave out predicated values for one of folds in cross-validation.

**Comment by frahik** [comment]
Could you give me a better explanation of your problem?
Greetings

**Comment by ghost** [comment]
Hi,

The problem came when I used BMTME to do the cross-validation (5 folds). I have 223 lines in 4 environments, and trying a multi-trait (4) model. I want to get the predicted value for each line in 4 environments for each trait. However, the pm$results$Predicated only showed predicted value for 178 (178*4*4= 2848 points). The BMOR function correctly produced all predicted values.

Thanks,
Jia

**Comment by frahik** [comment]
Sorry this not enough; Can you give the code that are you referring to?;
How do yo set the CV; and the configuration that are you giving to BMTME.
If the data you are handling is sensitive, please make it anonymous (Dummy
names), and try to use with a small dataset if the problem persists, share
that dummy dataset, for test your problem and to be able to solve this
problem in the best possible way, since currently the package tests do not
prescribe any problem.

**Comment by ghost** [comment]
Hi,

I think I figured it out. It was correct.

Thanks,
Jia

**Comment by frahik** [comment]
Excellent news!
Good luck with your research
